# Generated by Django 3.0.8 on 2020-07-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20200729_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='added_by',
        ),
    ]
